services:
    sylius.exporter.spreadsheet_writer_factory:
        class: FriendsOfSylius\SyliusImportExportPlugin\Writer\PortSpreadsheetWriterFactory

    sylius.exporter.spreadsheet_writer:
        class: FriendsOfSylius\SyliusImportExportPlugin\Writer\SpreadsheetWriter
        arguments:
            - '@sylius.exporter.spreadsheet_writer_factory'

    # Spreadsheet-Exporters
    sylius.exporter.countries.xlsx:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.spreadsheet_writer"
            - "@sylius.exporter.pluginpool.countries"
            - ["Id", "Code" ,"Enabled"]
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.country, format: xlsx }

    sylius.exporter.orders.xlsx:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.spreadsheet_writer"
            - "@sylius.exporter.pluginpool.orders"
            - ["Number", "State", "Product_list" , "Total" ,  "Currency_code", "Checkout_completed_at", "Checkout_state", "Payment_state", "Shipping_state", "Token_value", "Gender", "Full_name", "Email", "Telephone", "Shipping_address", "Billing_address" , "Customer_ip", "Notes"]
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.order, format: xlsx }

    sylius.exporter.customers.xlsx:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.spreadsheet_writer"
            - "@sylius.exporter.pluginpool.customers"
            - ["Email", "Email_canonical", "First_name" , "Last_name" ,  "Birthday", "Gender", "Phone_number", "Subscribed_to_newsletter"]
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.customer, format: xlsx }
