services:
    sylius.csv_writer:
        class: Port\Csv\CsvWriter

    sylius.exporter.csv_writer:
        class: FriendsOfSylius\SyliusImportExportPlugin\Writer\CsvWriter
        arguments:
            - '@sylius.csv_writer'

    # CSV-Exporters
    sylius.exporter.countries.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.csv_writer"
            - "@sylius.exporter.pluginpool.countries"
            - ["Id", "Code" ,"Enabled"]
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.country, format: csv }

    sylius.exporter.orders.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.csv_writer"
            - "@sylius.exporter.pluginpool.orders"
            - ["Number", "State", "Product_list" , "Total" ,  "Currency_code", "Checkout_completed_at", "Checkout_state", "Payment_state", "Shipping_state", "Token_value", "Gender", "Full_name", "Email", "Telephone", "Shipping_address", "Billing_address" , "Customer_ip", "Notes"]
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.order, format: csv }

    sylius.exporter.tax_categories.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.csv_writer"
            - "@sylius.exporter.pluginpool.tax_categories"
            - ["Id", "Code" ,"Name", "Description"]
            - "@sylius.exporters_transformer_pool" # Optional
        tags:
            - { name: sylius.exporter, type: sylius.tax_category, format: csv }

    sylius.exporter.customers.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.csv_writer"
            - "@sylius.exporter.pluginpool.customers"
            - ["Email", "Email_canonical", "First_name" , "Last_name" ,  "Birthday", "Gender", "Phone_number", "Subscribed_to_newsletter"]
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.customer, format: csv }
