services:
    sylius.factory.csv_reader:
        class: Port\Csv\CsvReaderFactory
        arguments:
            - 0

    # CSV-Importers
    sylius.importer.countries.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\ResourceImporter
        arguments:
            - "@sylius.factory.csv_reader"
            - "@sylius.manager.country"
            - "@sylius.processor.countries"
            - "@sylius.importer.result"
            - "%sylius.importer.batch_size%"
            - "%sylius.importer.fail_on_incomplete%"
            - "%sylius.importer.stop_on_failure%"
        tags:
            - { name: sylius.importer, type: country, format: csv }

    sylius.importer.customer_group.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\ResourceImporter
        arguments:
            - "@sylius.factory.csv_reader"
            - "@sylius.manager.customer_group"
            - "@sylius.processor.customer_groups"
            - "@sylius.importer.result"
            - "%sylius.importer.batch_size%"
            - "%sylius.importer.fail_on_incomplete%"
            - "%sylius.importer.stop_on_failure%"
        tags:
            - { name: sylius.importer, type: customer_group, format: csv }

    sylius.importer.payment_methods.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\ResourceImporter
        arguments:
            - "@sylius.factory.csv_reader"
            - "@sylius.manager.payment_method"
            - "@sylius.processor.payment_methods"
            - "@sylius.importer.result"
            - "%sylius.importer.batch_size%"
            - "%sylius.importer.fail_on_incomplete%"
            - "%sylius.importer.stop_on_failure%"
        tags:
            - { name: sylius.importer, type: payment_method, format: csv }

    sylius.importer.tax_categories.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\ResourceImporter
        arguments:
            - "@sylius.factory.csv_reader"
            - "@sylius.manager.tax_category"
            - "@sylius.processor.tax_categories"
            - "@sylius.importer.result"
            - "%sylius.importer.batch_size%"
            - "%sylius.importer.fail_on_incomplete%"
            - "%sylius.importer.stop_on_failure%"
        tags:
            - { name: sylius.importer, type: tax_category, format: csv }

    sylius.importer.customers.csv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\ResourceImporter
        arguments:
            - "@sylius.factory.csv_reader"
            - "@sylius.manager.customer"
            - "@sylius.processor.customers"
            - "@sylius.importer.result"
            - "%sylius.importer.batch_size%"
            - "%sylius.importer.fail_on_incomplete%"
            - "%sylius.importer.stop_on_failure%"
        tags:
            - { name: sylius.importer, type: customer, format: csv }
